### ISSUE TITLE
My HTML tags colors are missing

### ISSUE THREAD

**Issue by enzime4u** [konradkeska/subliminal-next#2]
Nice theme , but my html page colors are different than the one in the example.
The tags are color-less !?! 

Any idea why ?

**Comment by konradkeska** [comment]
I have decided to remove color highlight from semantic tags since they are not really a function call and what it is meant to highlight are function calls (React component invocations in TypeScript are highlighted, it is not possible to achieve in JavaScript from what I know). 

I am gonna update example picture as of the release of next version.

Hope I answered your question. Have a great day!

**Comment by enzime4u** [comment]
thank you , when do you plan to launch a new version ?

**Comment by konradkeska** [comment]
Probably in few days, still testing couple of things.

**Comment by enzime4u** [comment]
Thank you , looking forward to that !
